service: newsletter-signup

custom:
  tableName: ${self:service}-users-${opt:stage, self:provider.stage}
  corsOrigin: '*'

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    TABLE_NAME: ${self:custom.tableName}
    CORS_ORIGIN: ${self:custom.corsOrigin}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        'Fn::Join':
          - ':'
          - - 'arn:aws:dynamodb'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - table/${self:custom.tableName}

functions:
  post:
    handler: src/users.post
    events:
      - http:
          path: users
          method: POST
          cors: ${self:custom.corsOrigin}
    memorySize: 128

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table 
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1